### ISSUE TITLE
`newdelayplot` fails in demo1 tutorial?

### ISSUE THREAD

**Issue by drphilmarshall** [COSMOGRAIL/PyCS#11]
Hi @mtewes - we're learning `PyCS` by turning your tutorial scripts into an IPython notebook. [Check it out!](https://github.com/DarkEnergyScienceCollaboration/SLTimer/blob/master/notebooks/PyCS_Tutorial.ipynb) On cell 84, right at the end of Section 4, we're hitting a plotting problem:
```python
pycs.sim.plot.newdelayplot([disp, regdiff, spl], rplot=6.0, displaytext=True,
        filename = "fig_delays.pdf", refshifts=[{"colour":"gray", "shifts":(0, -5, -20, -70)}])
```
> ---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-84-1dfef2cc9309> in <module>()
      1 pycs.sim.plot.newdelayplot([disp, regdiff, spl], rplot=6.0, displaytext=True,
----> 2         filename = "fig_delays.pdf", refshifts=[{"colour":"gray", "shifts":(0, -5, -20, -70)}])
> 
> /Users/milanwilliams/PyCS/pycs/sim/plot.pyc in newdelayplot(plotlist, rplot, displaytext, hidedetails, showbias, showran, showlegend, text, figsize, left, right, top, bottom, wspace, hspace, txtstep, majorticksstep, filename, refshifts, refdelays, centershifts, ymin, hlines)
     84 
     85         # Some checks :
---> 86         objects = plotlist[0][0].objects
     87         for (delays, errors) in plotlist:
     88                 if delays.objects != objects or errors.objects != objects:
>
> TypeError: 'function' object has no attribute '__getitem__'

Any ideas what might be going on?

**Comment by mtewes** [comment]
Hi @drphilmarshall and @milanwilliams, your notebook looks great!
I'm having a look at it and at these issues *now*.

**Comment by mtewes** [comment]
Kudos @milanwilliams and @drphilmarshall for this awesome notebook, it's great to play with it and very well written!

About this specific error:
You try to pass the optimizing functions "regdiff" and "disp" to newdelayplot, but in fact newdelayplot just takes a list of tuples "(delays, errorbars)"... My fault, as in the demo I reused the optimizer-names "spl", "regdiff" and "disp" to designate these tuples.

At the end of Section 4, you don't have results from disp and regdiff, and so just pass it the results from spl (i.e., the spl-tuple defined one cell above...):

```
pycs.sim.plot.newdelayplot([spl], rplot=6.0, displaytext=True,
        filename = "fig_delays.pdf", refshifts=[{"colour":"gray", "shifts":(0, -5, -20, -70)}])
```
The arguments of newdelayplot:
http://pycs.readthedocs.io/en/latest/apidoc/pycs.sim.html#pycs.sim.plot.newdelayplot

**Comment by drphilmarshall** [comment]
Ahhhhh OK. That makes sense. @milanwilliams, can you please revisit the tutorial scripts and make sure that we have the right outputs to put in our `plotlist`?  Thanks!
