### ISSUE TITLE
MIssing `regdiff` attribute in optimizer?

### ISSUE THREAD

**Issue by drphilmarshall** [COSMOGRAIL/PyCS#12]
Hi @mtewes - another problem with the demo1 tutorial (or [our translation of it](https://github.com/DarkEnergyScienceCollaboration/SLTimer/blob/master/notebooks/PyCS_Tutorial.ipynb) :-) ):
```python
pycs.sim.run.multirun("copies", lcs, regdiff, optset="regdiff", tsrand=10.0)
```
> Starting the curve shifting on a single CPU, no multiprocessing...
>
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
<ipython-input-93-9e2063a46a35> in <module>()
----> 1 pycs.sim.run.multirun("copies", lcs, regdiff, optset="regdiff", tsrand=10.0)
>
> /Users/milanwilliams/PyCS/pycs/sim/run.pyc in multirun(simset, lcs, optfct, optset, tsrand, analyse, shuffle, keepopt, trace, verbose)
    387                                 for simlcs in simlcslist:
    388                                         pycs.gen.lc.shuffle(simlcs)
--> 389                         optfctouts = applyopt(optfct, simlcslist, verbose=verbose)
    390                         if shuffle: # We sort them, as they will be passed the constructor of runresuts.
    391                                 for simlcs in simlcslist:
>
> /Users/milanwilliams/PyCS/pycs/sim/run.pyc in applyopt(optfct, lcslist, ncpu, verbose)
     60                         print "Starting the curve shifting on a single CPU, no multiprocessing..."
     61                 start = time.time()
---> 62                 optfctouts = map(optfct, lcslist) # Ok to use optfct directly
     63                 print "Shifted %i simulations, using 1 CPU, time : %s" % (len(lcslist), pycs.gen.util.strtd(time.time() - start))
     64 
> 
> <ipython-input-83-f43ea6e8c596> in regdiff(lcs)
      4     return pycs.disp.topopt.opt_full(lcs, rawdispersionmethod, nit=5, verbose=True)
      5 def regdiff(lcs):
----> 6    return pycs.regdiff.multiopt.opt_ts(lcs, pd=5, scale=200.0, verbose=True)
> 
> AttributeError: 'module' object has no attribute 'regdiff'

**Comment by mtewes** [comment]
Hi @drphilmarshall and @milanwilliams,

what is missing here is an `import pycs.regdiff`.

(which is not imported by default because it has additional dependencies (pymc in this case))

If I replace the first cell by

```
import pycs.regdiff

for l in lcs:
    l.resetshifts()
    
lcs[1].shifttime(-7.0)
lcs[2].shifttime(-22.0)
lcs[3].shifttime(-65.0)

print(pycs.gen.lc.getnicetimedelays(lcs, separator="\n", sorted=True))

def regdiff(lcs):
    return pycs.regdiff.multiopt.opt_ts(lcs, pd=5, scale=200.0, verbose=True)

pycs.sim.run.multirun("copies", lcs, regdiff, optset="regdiff", tsrand=10.0)

```

... it seems to run fine.

**Comment by drphilmarshall** [comment]
Got it. @milanwilliams, can you please include the `import pycs.regdiff` statement and make sure your tutorial notebook runs and produces this plot? Thanks!
